### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by jadeoflagos** [zuri-training/fetch-metadata-team-90#21]
We have to work on a web page for the **documentation** together. The developers will give the technical content about building, deploying and managing the app, while the designers create the page (it will be linked to the footer and probably somewhere on the landing page).

**Comment by Veedified** [comment]
> We have to work on a web page for the **documentation** together. The developers will give the technical content about building, deploying and managing the app, while the designers create the page (it will be linked to the footer and probably somewhere on the landing page).

Noted!

**Comment by davidyayo92** [comment]
I concur

**Comment by SusanAlisa** [comment]
Has this been resolved?
