### ISSUE TITLE
Saved Data Page

### ISSUE THREAD

**Issue by Airin18** [zuri-training/fetch-metadata-team-90#27]
- [x] Build saved data page
- [x] A filter feature has been added to the **Saved Data** page. Please implement the changes in the page.

**Comment by tife-spec** [comment]
Nice🤩

**Comment by peachypeaches** [comment]
@Airin18 Please include an actual instruction or task when creating an issue. Take note of the updated issue for future reference

**Comment by peachypeaches** [comment]
@rodiyyah Have you taken care of this issue?

**Comment by rodiyyah** [comment]
The feature has been added and the webpage has been successfully built
