### ISSUE TITLE
Landing Page Modified!

### ISSUE THREAD

**Issue by davidyayo92** [zuri-training/fetch-metadata-team-90#30]
New homepage has been modified. The modified image has been pushed to the design folder. Implement new modifications and changes to landing pages https://www.figma.com/file/j5FgfRv5BeXPiNNGSXMXdw/Project-Team-90-team-library?node-id=422%3A2

**Comment by Veedified** [comment]
Noted!

**Comment by peachypeaches** [comment]
David, when creating an issue, please include an actual task e.g please implement new modification to landing page
