### ISSUE TITLE
Web app prototyping

### ISSUE THREAD

**Issue by Veedified** [zuri-training/fetch-metadata-team-90#43]
- [x] Complete web app prototype on all the pages

- [x]  double check for possible errors. 

@Jessheroine  @Veedified 
@zuri-training/designers

**Comment by Jessheroine** [comment]
Web app prototyped and interactions put in place as well as linking of all pages all done.

https://www.figma.com/file/j5FgfRv5BeXPiNNGSXMXdw/Project-Team-90-team-library?fuid=1108703475633576668
