### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by durobolu** [zuri-training/fetch-metadata-team-90#71]
Please help me cut the background image of faq section from the figma design and send

**Comment by davidyayo92** [comment]
which background image on the faq bolu? the faq has accordion

**Comment by durobolu** [comment]
Starting from where the Header "Frequently Asked Questions" is through the accordion to where the footer starts

**Comment by davidyayo92** [comment]
It has been added in the design folder.

**Comment by durobolu** [comment]
Okay

**Comment by MusaDauda** [comment]
Nice one
